apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      nodePort: 30080
  type: NodePort